[build]
builder = "NIXPACKS"

[deploy]
startCommand = "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.fileWatcherType none --browser.gatherUsageStats false"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10