[phases.setup]
nixPkgs = ["python311", "ffmpeg", "gcc"]
paths   = ["...", "/nix/var/nix/profiles/default/bin"]  # ここを追加

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"